// const fetchUrl = "https://www.wordgamedb.com/api/v1/words/random";

// // fetch(fetchUrl)
// //     .then(function (response) {
// //         if (response.ok) {
// //             console.log("fetch success");
// //             return response.json();
// //         }
// //     })
// //     .then(function (data) {
// //         console.log(data);
// //         randomWord = data;
// //         return randomWord;
// //     })
// //     .catch(function () {
// //         console.log("Error");
// //     });

// const answerContainer = document.querySelector(".answer-container");

// const getRandomWord = async () => {
//     let randomWord;
//     console.log("Function Working");
//     await fetch(fetchUrl)
//         .then((response) => response.json())
//         .then((data) => {
//             randomWord = data;
//         })
//         .catch((e) => {
//             console.log("Error");
//         });
//     for (let i = 1; i <= randomWord.numLetters; i++) {
//         console.log(i);
//         answerContainer.appendChild(document.createElement("span"));
//     }
// };

// getRandomWord();

// const obj = {
//     0: {
//         _id: "5fee49e11935ff7c8aa1660b",
//         word: "cobra",
//         category: "animal",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     1: {
//         _id: "5ffa1780c0831cbe1460e29d",
//         word: "tiger",
//         category: "animal",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     2: {
//         _id: "5fee4a241935ff7c8aa1660d",
//         word: "pizza",
//         category: "food",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     3: {
//         _id: "5fee49681935ff7c8aa16607",
//         word: "gecko",
//         category: "animal",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     4: {
//         _id: "5fee49a21935ff7c8aa16609",
//         word: "dolphin",
//         category: "animal",
//         numLetters: 7,
//         numSyllables: 2,
//         __v: 0,
//     },
//     5: {
//         _id: "5ffa149dc0831cbe1460e287",
//         word: "hockey",
//         category: "sport",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     6: {
//         _id: "5ffa14e3c0831cbe1460e289",
//         word: "badminton",
//         category: "sport",
//         numLetters: 9,
//         numSyllables: 3,
//         __v: 0,
//     },
//     7: {
//         _id: "5ffa1ac1c0831cbe1460e2bc",
//         word: "botswana",
//         category: "country",
//         numLetters: 8,
//         numSyllables: 3,
//         __v: 0,
//     },
//     8: {
//         _id: "61e4cdb7ffe8b104fb77ef41",
//         word: "mule",
//         category: "animal",
//         numLetters: 4,
//         numSyllables: 1,
//         __v: 0,
//     },
//     9: {
//         _id: "61e4ce860891be058c6d2a0d",
//         word: "hare",
//         category: "animal",
//         numLetters: 4,
//         numSyllables: 1,
//         __v: 0,
//     },
//     10: {
//         _id: "61e4d26e872ada081fccf417",
//         word: "mongolia",
//         category: "country",
//         numLetters: 8,
//         numSyllables: 4,
//         __v: 0,
//     },
//     11: {
//         _id: "61e4e06bbc67f00fbabf32bd",
//         word: "bacon",
//         category: "food",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     12: {
//         _id: "5fee4aba1935ff7c8aa16612",
//         word: "lasagna",
//         category: "food",
//         numLetters: 7,
//         numSyllables: 3,
//         __v: 0,
//     },
//     13: {
//         _id: "5ffa140dc0831cbe1460e281",
//         word: "cricket",
//         category: "sport",
//         numLetters: 7,
//         numSyllables: 2,
//         __v: 0,
//     },
//     14: {
//         _id: "5ffa14f7c0831cbe1460e28a",
//         word: "tennis",
//         category: "sport",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     15: {
//         _id: "5ffa16abc0831cbe1460e293",
//         word: "fern",
//         category: "plant",
//         numLetters: 4,
//         numSyllables: 1,
//         __v: 0,
//     },
//     16: {
//         _id: "5ffa16c4c0831cbe1460e294",
//         word: "hoya",
//         category: "plant",
//         numLetters: 4,
//         numSyllables: 2,
//         __v: 0,
//     },
//     17: {
//         _id: "5ffa195bc0831cbe1460e2b0",
//         word: "cheese",
//         category: "food",
//         numLetters: 6,
//         numSyllables: 1,
//         __v: 0,
//     },
//     18: {
//         _id: "5ffa1af6c0831cbe1460e2be",
//         word: "chad",
//         category: "country",
//         numLetters: 4,
//         numSyllables: 1,
//         __v: 0,
//     },
//     19: {
//         _id: "61e4dc38a156ef0c62e6ff06",
//         word: "cake",
//         category: "food",
//         numLetters: 4,
//         numSyllables: 1,
//         __v: 0,
//     },
//     20: {
//         _id: "5fee4a871935ff7c8aa16610",
//         word: "waffles",
//         category: "food",
//         numLetters: 7,
//         numSyllables: 2,
//         __v: 0,
//     },
//     21: {
//         _id: "5fee4b041935ff7c8aa16614",
//         word: "canada",
//         category: "country",
//         numLetters: 6,
//         numSyllables: 3,
//         __v: 0,
//     },
//     22: {
//         _id: "5ffa174ac0831cbe1460e29a",
//         word: "chicken",
//         category: "animal",
//         numLetters: 7,
//         numSyllables: 2,
//         __v: 0,
//     },
//     23: {
//         _id: "5ffa1763c0831cbe1460e29b",
//         word: "goat",
//         category: "animal",
//         numLetters: 4,
//         numSyllables: 1,
//         __v: 0,
//     },
//     24: {
//         _id: "5ffa18f4c0831cbe1460e2ab",
//         word: "cucumber",
//         category: "food",
//         numLetters: 8,
//         numSyllables: 3,
//         __v: 0,
//     },
//     25: {
//         _id: "5ffa1932c0831cbe1460e2ae",
//         word: "spinach",
//         category: "food",
//         numLetters: 7,
//         numSyllables: 2,
//         __v: 0,
//     },
//     26: {
//         _id: "5ffa1a96c0831cbe1460e2ba",
//         word: "algeria",
//         category: "country",
//         numLetters: 7,
//         numSyllables: 4,
//         __v: 0,
//     },
//     27: {
//         _id: "61e4d1966e4ae307bd479a80",
//         word: "spain",
//         category: "country",
//         numLetters: 5,
//         numSyllables: 1,
//         __v: 0,
//     },
//     28: {
//         _id: "5fee4a681935ff7c8aa1660f",
//         word: "pho",
//         category: "food",
//         numLetters: 3,
//         numSyllables: 1,
//         __v: 0,
//     },
//     29: {
//         _id: "5fee4b331935ff7c8aa16616",
//         word: "brazil",
//         category: "country",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     30: {
//         _id: "5ffa1469c0831cbe1460e285",
//         word: "baseball",
//         category: "sport",
//         numLetters: 8,
//         numSyllables: 2,
//         __v: 0,
//     },
//     31: {
//         _id: "5ffa1774c0831cbe1460e29c",
//         word: "lion",
//         category: "animal",
//         numLetters: 4,
//         numSyllables: 2,
//         __v: 0,
//     },
//     32: {
//         _id: "5ffa18e8c0831cbe1460e2aa",
//         word: "egg",
//         category: "food",
//         numLetters: 3,
//         numSyllables: 1,
//         __v: 0,
//     },
//     33: {
//         _id: "5ffa19f5c0831cbe1460e2b5",
//         word: "peru",
//         category: "country",
//         numLetters: 4,
//         numSyllables: 2,
//         __v: 0,
//     },
//     34: {
//         _id: "61e4d0e1d373da0724e3d47d",
//         word: "mouse",
//         category: "animal",
//         numLetters: 5,
//         numSyllables: 1,
//         __v: 0,
//     },
//     35: {
//         _id: "5fee48761935ff7c8aa16603",
//         word: "lily",
//         category: "plant",
//         numLetters: 4,
//         numSyllables: 2,
//         __v: 0,
//     },
//     36: {
//         _id: "5fee4aa11935ff7c8aa16611",
//         word: "burger",
//         category: "food",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     37: {
//         _id: "5ffa13f2c0831cbe1460e280",
//         word: "basketball",
//         category: "sport",
//         numLetters: 10,
//         numSyllables: 3,
//         __v: 0,
//     },
//     38: {
//         _id: "5fee4a3e1935ff7c8aa1660e",
//         word: "hummus",
//         category: "food",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     39: {
//         _id: "5fee4aed1935ff7c8aa16613",
//         word: "japan",
//         category: "country",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     40: {
//         _id: "5ffa157ec0831cbe1460e28d",
//         word: "bamboo",
//         category: "plant",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     41: {
//         _id: "5ffa18a0c0831cbe1460e2a6",
//         word: "soup",
//         category: "food",
//         numLetters: 4,
//         numSyllables: 1,
//         __v: 0,
//     },
//     42: {
//         _id: "5ffa1980c0831cbe1460e2b1",
//         word: "spaghetti",
//         category: "food",
//         numLetters: 9,
//         numSyllables: 3,
//         __v: 0,
//     },
//     43: {
//         _id: "5ffa19e4c0831cbe1460e2b4",
//         word: "panama",
//         category: "country",
//         numLetters: 6,
//         numSyllables: 3,
//         __v: 0,
//     },
//     44: {
//         _id: "5ffa1a05c0831cbe1460e2b6",
//         word: "argentina",
//         category: "country",
//         numLetters: 9,
//         numSyllables: 4,
//         __v: 0,
//     },
//     45: {
//         _id: "5ffa1b54c0831cbe1460e2c1",
//         word: "lebanon",
//         category: "country",
//         numLetters: 7,
//         numSyllables: 3,
//         __v: 0,
//     },
//     46: {
//         _id: "5fee49ba1935ff7c8aa1660a",
//         word: "squirrel",
//         category: "animal",
//         numLetters: 8,
//         numSyllables: 2,
//         __v: 0,
//     },
//     47: {
//         _id: "5fee46fe89ccca6a122a3bf4",
//         word: "cactus",
//         category: "plant",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     48: {
//         _id: "5fee493b1935ff7c8aa16606",
//         word: "ivy",
//         category: "plant",
//         numLetters: 3,
//         numSyllables: 2,
//         __v: 0,
//     },
//     49: {
//         _id: "5ffa17bac0831cbe1460e29f",
//         word: "rabbit",
//         category: "animal",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     50: {
//         _id: "5ffa17e0c0831cbe1460e2a1",
//         word: "ferret",
//         category: "animal",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     51: {
//         _id: "5ffa19b8c0831cbe1460e2b2",
//         word: "mexico",
//         category: "country",
//         numLetters: 6,
//         numSyllables: 3,
//         __v: 0,
//     },
//     52: {
//         _id: "61e4cf9fe1ce040656f30476",
//         word: "goose",
//         category: "animal",
//         numLetters: 5,
//         numSyllables: 1,
//         __v: 0,
//     },
//     53: {
//         _id: "5fee4b741935ff7c8aa16618",
//         word: "denmark",
//         category: "country",
//         numLetters: 7,
//         numSyllables: 2,
//         __v: 0,
//     },
//     54: {
//         _id: "5ffa14adc0831cbe1460e288",
//         word: "lacrosse",
//         category: "sport",
//         numLetters: 8,
//         numSyllables: 2,
//         __v: 0,
//     },
//     55: {
//         _id: "5ffa173cc0831cbe1460e299",
//         word: "horse",
//         category: "animal",
//         numLetters: 5,
//         numSyllables: 1,
//         __v: 0,
//     },
//     56: {
//         _id: "5ffa17c9c0831cbe1460e2a0",
//         word: "hamster",
//         category: "animal",
//         numLetters: 7,
//         numSyllables: 2,
//         __v: 0,
//     },
//     57: {
//         _id: "5ffa17fdc0831cbe1460e2a3",
//         word: "tortoise",
//         category: "animal",
//         numLetters: 8,
//         numSyllables: 2,
//         __v: 0,
//     },
//     58: {
//         _id: "61e4dab6158ea30b61866fa8",
//         word: "stew",
//         category: "food",
//         numLetters: 4,
//         numSyllables: 1,
//         __v: 0,
//     },
//     59: {
//         _id: "620f16608b1cebd03f9bf928",
//         word: "possum",
//         category: "animal",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     60: {
//         _id: "5ffa152fc0831cbe1460e28c",
//         word: "golf",
//         category: "sport",
//         numLetters: 4,
//         numSyllables: 1,
//         __v: 0,
//     },
//     61: {
//         _id: "5ffa1722c0831cbe1460e297",
//         word: "cow",
//         category: "animal",
//         numLetters: 3,
//         numSyllables: 1,
//         __v: 0,
//     },
//     62: {
//         _id: "5ffa18c0c0831cbe1460e2a8",
//         word: "bread",
//         category: "food",
//         numLetters: 5,
//         numSyllables: 1,
//         __v: 0,
//     },
//     63: {
//         _id: "5ffa190ec0831cbe1460e2ac",
//         word: "eggplant",
//         category: "food",
//         numLetters: 8,
//         numSyllables: 2,
//         __v: 0,
//     },
//     64: {
//         _id: "61e4e22cd73acf1151419f2c",
//         word: "pie",
//         category: "food",
//         numLetters: 3,
//         numSyllables: 1,
//         __v: 0,
//     },
//     65: {
//         _id: "5ffa185cc0831cbe1460e2a5",
//         word: "crocodile",
//         category: "animal",
//         numLetters: 9,
//         numSyllables: 3,
//         __v: 0,
//     },
//     66: {
//         _id: "5ffa18cfc0831cbe1460e2a9",
//         word: "rice",
//         category: "food",
//         numLetters: 4,
//         numSyllables: 1,
//         __v: 0,
//     },
//     67: {
//         _id: "61e4dcb3effcb80cbae38742",
//         word: "curry",
//         category: "food",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     68: {
//         _id: "61e4e5425f32941426557825",
//         word: "melon",
//         category: "food",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     69: {
//         _id: "5fee4a091935ff7c8aa1660c",
//         word: "parrot",
//         category: "animal",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     70: {
//         _id: "5ffa1addc0831cbe1460e2bd",
//         word: "cameroon",
//         category: "country",
//         numLetters: 8,
//         numSyllables: 3,
//         __v: 0,
//     },
//     71: {
//         _id: "5fee4b1d1935ff7c8aa16615",
//         word: "vietnam",
//         category: "country",
//         numLetters: 7,
//         numSyllables: 3,
//         __v: 0,
//     },
//     72: {
//         _id: "5ffa19d3c0831cbe1460e2b3",
//         word: "guatemala",
//         category: "country",
//         numLetters: 9,
//         numSyllables: 4,
//         __v: 0,
//     },
//     73: {
//         _id: "5ffa13cbc0831cbe1460e27f",
//         word: "soccer",
//         category: "sport",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     74: {
//         _id: "5ffa1707c0831cbe1460e295",
//         word: "dog",
//         category: "animal",
//         numLetters: 3,
//         numSyllables: 1,
//         __v: 0,
//     },
//     75: {
//         _id: "5ffa1789c0831cbe1460e29e",
//         word: "bear",
//         category: "animal",
//         numLetters: 4,
//         numSyllables: 1,
//         __v: 0,
//     },
//     76: {
//         _id: "5ffa183dc0831cbe1460e2a4",
//         word: "alligator",
//         category: "animal",
//         numLetters: 9,
//         numSyllables: 4,
//         __v: 0,
//     },
//     77: {
//         _id: "5ffa1941c0831cbe1460e2af",
//         word: "onion",
//         category: "food",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     78: {
//         _id: "5ffa1a6ec0831cbe1460e2b9",
//         word: "china",
//         category: "country",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     79: {
//         _id: "5ffa1aa9c0831cbe1460e2bb",
//         word: "benin",
//         category: "country",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     80: {
//         _id: "61e4d2077304d207ebccd8fc",
//         word: "ecuador",
//         category: "country",
//         numLetters: 7,
//         numSyllables: 3,
//         __v: 0,
//     },
//     81: {
//         _id: "5fee47b01935ff7c8aa16602",
//         word: "moss",
//         category: "plant",
//         numLetters: 4,
//         numSyllables: 1,
//         __v: 0,
//     },
//     82: {
//         _id: "5fee4b501935ff7c8aa16617",
//         word: "russia",
//         category: "country",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     83: {
//         _id: "5fee49881935ff7c8aa16608",
//         word: "bobcat",
//         category: "animal",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     84: {
//         _id: "5fee48971935ff7c8aa16604",
//         word: "yucca",
//         category: "plant",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     85: {
//         _id: "5ffa159dc0831cbe1460e28e",
//         word: "palm",
//         category: "plant",
//         numLetters: 4,
//         numSyllables: 1,
//         __v: 0,
//     },
//     86: {
//         _id: "5ffa15ccc0831cbe1460e28f",
//         word: "pothos",
//         category: "plant",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     87: {
//         _id: "5ffa1713c0831cbe1460e296",
//         word: "cat",
//         category: "animal",
//         numLetters: 3,
//         numSyllables: 1,
//         __v: 0,
//     },
//     88: {
//         _id: "5ffa1731c0831cbe1460e298",
//         word: "pig",
//         category: "animal",
//         numLetters: 3,
//         numSyllables: 1,
//         __v: 0,
//     },
//     89: {
//         _id: "5ffa18aec0831cbe1460e2a7",
//         word: "salad",
//         category: "food",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     90: {
//         _id: "5ffa1b15c0831cbe1460e2bf",
//         word: "ghana",
//         category: "country",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     91: {
//         _id: "61e4d08d92bc3f06c9c3f65b",
//         word: "moose",
//         category: "animal",
//         numLetters: 5,
//         numSyllables: 1,
//         __v: 0,
//     },
//     92: {
//         _id: "61e4e64d7ddc9714c3ea048f",
//         word: "naan",
//         category: "food",
//         numLetters: 4,
//         numSyllables: 1,
//         __v: 0,
//     },
//     93: {
//         _id: "5ffa17efc0831cbe1460e2a2",
//         word: "turtle",
//         category: "animal",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     94: {
//         _id: "5ffa1923c0831cbe1460e2ad",
//         word: "lettuce",
//         category: "food",
//         numLetters: 7,
//         numSyllables: 2,
//         __v: 0,
//     },
//     95: {
//         _id: "5ffa1a1ac0831cbe1460e2b7",
//         word: "venezuela",
//         category: "country",
//         numLetters: 9,
//         numSyllables: 4,
//         __v: 0,
//     },
//     96: {
//         _id: "5ffa1a2cc0831cbe1460e2b8",
//         word: "germany",
//         category: "country",
//         numLetters: 7,
//         numSyllables: 3,
//         __v: 0,
//     },
//     97: {
//         _id: "5ffa1b35c0831cbe1460e2c0",
//         word: "india",
//         category: "country",
//         numLetters: 5,
//         numSyllables: 3,
//         __v: 0,
//     },
//     98: {
//         _id: "61e4e85f1cac29168b1e0643",
//         word: "kiwi",
//         category: "food",
//         numLetters: 4,
//         numSyllables: 2,
//         __v: 0,
//     },
//     99: {
//         _id: "5fee48c81935ff7c8aa16605",
//         word: "orchid",
//         category: "plant",
//         numLetters: 6,
//         numSyllables: 2,
//         __v: 0,
//     },
//     100: {
//         _id: "5ffa142bc0831cbe1460e282",
//         word: "swimming",
//         category: "sport",
//         numLetters: 8,
//         numSyllables: 2,
//         __v: 0,
//     },
//     101: {
//         _id: "5ffa1485c0831cbe1460e286",
//         word: "football",
//         category: "sport",
//         numLetters: 8,
//         numSyllables: 2,
//         __v: 0,
//     },
//     102: {
//         _id: "61e4d3f696344a09221f2c7f",
//         word: "honey",
//         category: "food",
//         numLetters: 5,
//         numSyllables: 2,
//         __v: 0,
//     },
//     103: {
//         _id: "61e4d459516c460946da7e71",
//         word: "steak",
//         category: "food",
//         numLetters: 5,
//         numSyllables: 1,
//         __v: 0,
//     },
//     104: {
//         _id: "61e4e360cd037612889aaafb",
//         word: "gelato",
//         category: "food",
//         numLetters: 6,
//         numSyllables: 3,
//         __v: 0,
//     },
//     105: {
//         _id: "5ffa1510c0831cbe1460e28b",
//         word: "volleyball",
//         category: "sport",
//         numLetters: 10,
//         numSyllables: 3,
//         __v: 0,
//     },
//     106: {
//         _id: "5ffa15edc0831cbe1460e290",
//         word: "monstera",
//         category: "plant",
//         numLetters: 8,
//         numSyllables: 3,
//         __v: 0,
//     },
//     107: {
//         _id: "5ffa1618c0831cbe1460e291",
//         word: "philodendron",
//         category: "plant",
//         numLetters: 12,
//         numSyllables: 4,
//         __v: 0,
//     },
//     108: {
//         _id: "5ffa1643c0831cbe1460e292",
//         word: "calathea",
//         category: "plant",
//         numLetters: 8,
//         numSyllables: 4,
//         __v: 0,
//     },
// };
// console.log(obj);
// const keyList = Object.keys(obj);
// const lst = [];
// for (key of keyList) {
//     const insideLst = {};
//     insideLst.word = obj[key]["word"];
//     insideLst.category = obj[key]["category"];
//     insideLst.numLetter = obj[key]["numLetters"];
//     lst.push(insideLst);
// }
// console.log(lst);

const wordList = [
    { word: "cobra", category: "animal", numLetter: 5 },
    { word: "tiger", category: "animal", numLetter: 5 },
    { word: "pizza", category: "food", numLetter: 5 },
    { word: "gecko", category: "animal", numLetter: 5 },
    { word: "dolphin", category: "animal", numLetter: 7 },
    { word: "hockey", category: "sport", numLetter: 6 },
    { word: "badminton", category: "sport", numLetter: 9 },
    { word: "botswana", category: "country", numLetter: 8 },
    { word: "mule", category: "animal", numLetter: 4 },
    { word: "hare", category: "animal", numLetter: 4 },
    { word: "mongolia", category: "country", numLetter: 8 },
    { word: "bacon", category: "food", numLetter: 5 },
    { word: "lasagna", category: "food", numLetter: 7 },
    { word: "cricket", category: "sport", numLetter: 7 },
    { word: "tennis", category: "sport", numLetter: 6 },
    { word: "fern", category: "plant", numLetter: 4 },
    { word: "hoya", category: "plant", numLetter: 4 },
    { word: "cheese", category: "food", numLetter: 6 },
    { word: "chad", category: "country", numLetter: 4 },
    { word: "cake", category: "food", numLetter: 4 },
    { word: "waffles", category: "food", numLetter: 7 },
    { word: "canada", category: "country", numLetter: 6 },
    { word: "chicken", category: "animal", numLetter: 7 },
    { word: "goat", category: "animal", numLetter: 4 },
    { word: "cucumber", category: "food", numLetter: 8 },
    { word: "spinach", category: "food", numLetter: 7 },
    { word: "algeria", category: "country", numLetter: 7 },
    { word: "spain", category: "country", numLetter: 5 },
    { word: "pho", category: "food", numLetter: 3 },
    { word: "brazil", category: "country", numLetter: 6 },
    { word: "baseball", category: "sport", numLetter: 8 },
    { word: "lion", category: "animal", numLetter: 4 },
    { word: "egg", category: "food", numLetter: 3 },
    { word: "peru", category: "country", numLetter: 4 },
    { word: "mouse", category: "animal", numLetter: 5 },
    { word: "lily", category: "plant", numLetter: 4 },
    { word: "burger", category: "food", numLetter: 6 },
    { word: "basketball", category: "sport", numLetter: 10 },
    { word: "hummus", category: "food", numLetter: 6 },
    { word: "japan", category: "country", numLetter: 5 },
    { word: "bamboo", category: "plant", numLetter: 6 },
    { word: "soup", category: "food", numLetter: 4 },
    { word: "spaghetti", category: "food", numLetter: 9 },
    { word: "panama", category: "country", numLetter: 6 },
    { word: "argentina", category: "country", numLetter: 9 },
    { word: "lebanon", category: "country", numLetter: 7 },
    { word: "squirrel", category: "animal", numLetter: 8 },
    { word: "cactus", category: "plant", numLetter: 5 },
    { word: "ivy", category: "plant", numLetter: 3 },
    { word: "rabbit", category: "animal", numLetter: 6 },
    { word: "ferret", category: "animal", numLetter: 6 },
    { word: "mexico", category: "country", numLetter: 6 },
    { word: "goose", category: "animal", numLetter: 5 },
    { word: "denmark", category: "country", numLetter: 7 },
    { word: "lacrosse", category: "sport", numLetter: 8 },
    { word: "horse", category: "animal", numLetter: 5 },
    { word: "hamster", category: "animal", numLetter: 7 },
    { word: "tortoise", category: "animal", numLetter: 8 },
    { word: "stew", category: "food", numLetter: 4 },
    { word: "possum", category: "animal", numLetter: 6 },
    { word: "golf", category: "sport", numLetter: 4 },
    { word: "cow", category: "animal", numLetter: 3 },
    { word: "bread", category: "food", numLetter: 5 },
    { word: "eggplant", category: "food", numLetter: 8 },
    { word: "pie", category: "food", numLetter: 3 },
    { word: "crocodile", category: "animal", numLetter: 9 },
    { word: "rice", category: "food", numLetter: 4 },
    { word: "curry", category: "food", numLetter: 5 },
    { word: "melon", category: "food", numLetter: 5 },
    { word: "parrot", category: "animal", numLetter: 6 },
    { word: "cameroon", category: "country", numLetter: 8 },
    { word: "vietnam", category: "country", numLetter: 7 },
    { word: "guatemala", category: "country", numLetter: 9 },
    { word: "soccer", category: "sport", numLetter: 6 },
    { word: "dog", category: "animal", numLetter: 3 },
    { word: "bear", category: "animal", numLetter: 4 },
    { word: "alligator", category: "animal", numLetter: 9 },
    { word: "onion", category: "food", numLetter: 5 },
    { word: "china", category: "country", numLetter: 5 },
    { word: "benin", category: "country", numLetter: 5 },
    { word: "ecuador", category: "country", numLetter: 7 },
    { word: "moss", category: "plant", numLetter: 4 },
    { word: "russia", category: "country", numLetter: 6 },
    { word: "bobcat", category: "animal", numLetter: 6 },
    { word: "yucca", category: "plant", numLetter: 5 },
    { word: "palm", category: "plant", numLetter: 4 },
    { word: "pothos", category: "plant", numLetter: 6 },
    { word: "cat", category: "animal", numLetter: 3 },
    { word: "pig", category: "animal", numLetter: 3 },
    { word: "salad", category: "food", numLetter: 5 },
    { word: "ghana", category: "country", numLetter: 5 },
    { word: "moose", category: "animal", numLetter: 5 },
    { word: "naan", category: "food", numLetter: 4 },
    { word: "turtle", category: "animal", numLetter: 6 },
    { word: "lettuce", category: "food", numLetter: 7 },
    { word: "venezuela", category: "country", numLetter: 9 },
    { word: "germany", category: "country", numLetter: 7 },
    { word: "india", category: "country", numLetter: 5 },
    { word: "kiwi", category: "food", numLetter: 4 },
    { word: "orchid", category: "plant", numLetter: 6 },
    { word: "swimming", category: "sport", numLetter: 8 },
    { word: "football", category: "sport", numLetter: 8 },
    { word: "honey", category: "food", numLetter: 5 },
    { word: "steak", category: "food", numLetter: 5 },
    { word: "gelato", category: "food", numLetter: 6 },
    { word: "volleyball", category: "sport", numLetter: 10 },
    { word: "monstera", category: "plant", numLetter: 8 },
    { word: "philodendron", category: "plant", numLetter: 12 },
    { word: "calathea", category: "plant", numLetter: 8 },
];
