const wordList = [
    { word: "cobra", category: "animal", numLetter: 5 },
    { word: "tiger", category: "animal", numLetter: 5 },
    { word: "pizza", category: "food", numLetter: 5 },
    { word: "gecko", category: "animal", numLetter: 5 },
    { word: "dolphin", category: "animal", numLetter: 7 },
    { word: "hockey", category: "sport", numLetter: 6 },
    { word: "badminton", category: "sport", numLetter: 9 },
    { word: "botswana", category: "country", numLetter: 8 },
    { word: "mule", category: "animal", numLetter: 4 },
    { word: "hare", category: "animal", numLetter: 4 },
    { word: "mongolia", category: "country", numLetter: 8 },
    { word: "bacon", category: "food", numLetter: 5 },
    { word: "lasagna", category: "food", numLetter: 7 },
    { word: "cricket", category: "sport", numLetter: 7 },
    { word: "tennis", category: "sport", numLetter: 6 },
    { word: "fern", category: "plant", numLetter: 4 },
    { word: "hoya", category: "plant", numLetter: 4 },
    { word: "cheese", category: "food", numLetter: 6 },
    { word: "chad", category: "country", numLetter: 4 },
    { word: "cake", category: "food", numLetter: 4 },
    { word: "waffles", category: "food", numLetter: 7 },
    { word: "canada", category: "country", numLetter: 6 },
    { word: "chicken", category: "animal", numLetter: 7 },
    { word: "goat", category: "animal", numLetter: 4 },
    { word: "cucumber", category: "food", numLetter: 8 },
    { word: "spinach", category: "food", numLetter: 7 },
    { word: "algeria", category: "country", numLetter: 7 },
    { word: "spain", category: "country", numLetter: 5 },
    { word: "pho", category: "food", numLetter: 3 },
    { word: "brazil", category: "country", numLetter: 6 },
    { word: "baseball", category: "sport", numLetter: 8 },
    { word: "lion", category: "animal", numLetter: 4 },
    { word: "egg", category: "food", numLetter: 3 },
    { word: "peru", category: "country", numLetter: 4 },
    { word: "mouse", category: "animal", numLetter: 5 },
    { word: "lily", category: "plant", numLetter: 4 },
    { word: "burger", category: "food", numLetter: 6 },
    { word: "basketball", category: "sport", numLetter: 10 },
    { word: "hummus", category: "food", numLetter: 6 },
    { word: "japan", category: "country", numLetter: 5 },
    { word: "bamboo", category: "plant", numLetter: 6 },
    { word: "soup", category: "food", numLetter: 4 },
    { word: "spaghetti", category: "food", numLetter: 9 },
    { word: "panama", category: "country", numLetter: 6 },
    { word: "argentina", category: "country", numLetter: 9 },
    { word: "lebanon", category: "country", numLetter: 7 },
    { word: "squirrel", category: "animal", numLetter: 8 },
    { word: "cactus", category: "plant", numLetter: 5 },
    { word: "ivy", category: "plant", numLetter: 3 },
    { word: "rabbit", category: "animal", numLetter: 6 },
    { word: "ferret", category: "animal", numLetter: 6 },
    { word: "mexico", category: "country", numLetter: 6 },
    { word: "goose", category: "animal", numLetter: 5 },
    { word: "denmark", category: "country", numLetter: 7 },
    { word: "lacrosse", category: "sport", numLetter: 8 },
    { word: "horse", category: "animal", numLetter: 5 },
    { word: "hamster", category: "animal", numLetter: 7 },
    { word: "tortoise", category: "animal", numLetter: 8 },
    { word: "stew", category: "food", numLetter: 4 },
    { word: "possum", category: "animal", numLetter: 6 },
    { word: "golf", category: "sport", numLetter: 4 },
    { word: "cow", category: "animal", numLetter: 3 },
    { word: "bread", category: "food", numLetter: 5 },
    { word: "eggplant", category: "food", numLetter: 8 },
    { word: "pie", category: "food", numLetter: 3 },
    { word: "crocodile", category: "animal", numLetter: 9 },
    { word: "rice", category: "food", numLetter: 4 },
    { word: "curry", category: "food", numLetter: 5 },
    { word: "melon", category: "food", numLetter: 5 },
    { word: "parrot", category: "animal", numLetter: 6 },
    { word: "cameroon", category: "country", numLetter: 8 },
    { word: "vietnam", category: "country", numLetter: 7 },
    { word: "guatemala", category: "country", numLetter: 9 },
    { word: "soccer", category: "sport", numLetter: 6 },
    { word: "dog", category: "animal", numLetter: 3 },
    { word: "bear", category: "animal", numLetter: 4 },
    { word: "alligator", category: "animal", numLetter: 9 },
    { word: "onion", category: "food", numLetter: 5 },
    { word: "china", category: "country", numLetter: 5 },
    { word: "benin", category: "country", numLetter: 5 },
    { word: "ecuador", category: "country", numLetter: 7 },
    { word: "moss", category: "plant", numLetter: 4 },
    { word: "russia", category: "country", numLetter: 6 },
    { word: "bobcat", category: "animal", numLetter: 6 },
    { word: "yucca", category: "plant", numLetter: 5 },
    { word: "palm", category: "plant", numLetter: 4 },
    { word: "pothos", category: "plant", numLetter: 6 },
    { word: "cat", category: "animal", numLetter: 3 },
    { word: "pig", category: "animal", numLetter: 3 },
    { word: "salad", category: "food", numLetter: 5 },
    { word: "ghana", category: "country", numLetter: 5 },
    { word: "moose", category: "animal", numLetter: 5 },
    { word: "naan", category: "food", numLetter: 4 },
    { word: "turtle", category: "animal", numLetter: 6 },
    { word: "lettuce", category: "food", numLetter: 7 },
    { word: "venezuela", category: "country", numLetter: 9 },
    { word: "germany", category: "country", numLetter: 7 },
    { word: "india", category: "country", numLetter: 5 },
    { word: "kiwi", category: "food", numLetter: 4 },
    { word: "orchid", category: "plant", numLetter: 6 },
    { word: "swimming", category: "sport", numLetter: 8 },
    { word: "football", category: "sport", numLetter: 8 },
    { word: "honey", category: "food", numLetter: 5 },
    { word: "steak", category: "food", numLetter: 5 },
    { word: "gelato", category: "food", numLetter: 6 },
    { word: "volleyball", category: "sport", numLetter: 10 },
    { word: "monstera", category: "plant", numLetter: 8 },
    { word: "philodendron", category: "plant", numLetter: 12 },
    { word: "calathea", category: "plant", numLetter: 8 },
];

const ranNum = Math.floor(Math.random() * (wordList.length - 1));
const wordSet = wordList[ranNum];

const answerContainer = document.querySelector(".answer-container");

for (let i = 1; i <= wordSet.numLetter; i++) {
    answerContainer.appendChild(document.createElement("span"));
}

// for (let i = 1; i <= 10; i++) {
//     answerContainer.appendChild(document.createElement("span"));
// }
